name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up kubectl
        uses: azure/setup-kub
::contentReference[oaicite:1]{index=1}
 
