apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 539935451710.dkr.ecr.us-west-2.amazonaws.com/my-app-repo:latest
        ports:
        - containerPort: 3000